---
title: "Yearpricesraper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
porscheurl = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1"
porschedata = read_html(porscheurl)
porschedata
```

```{r}
porschelisting = gettitle(porschedata)
getprice = function(x) {
  x %>%
  html_nodes(".s-item__price")%>%
  html_text()
}
porscheprice = priceadjust(getprice(porschedata))
porscheprice


porschelisting
```
```{r}
yearget = function(x) {
  year1 = str_extract(x, pattern = "[[:digit:]]{4}")
  year2 = as.numeric(year1)
  year2
}
yearget(porschelisting)

```
```{r}
porscheyear = yearget(porschelisting)
porscheprice = priceadjust(getprice(porschedata))
porscheyear
porscheprice
```
```{r,eval = FALSE}
install.packages("ggplot2")
install.packages("plotly")
```
```{r}
library(ggplot2)
```

```{r}

```
```{r}
"https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1"

"https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=2"

"https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=1"

```
```{r}
install.packages("Stack")
```

```{r, eval=FALSE}
page1 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=1"

page2 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=2"

page3 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=3"

page4 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Porsche+911&rt=nc&LH_BIN=1&UF_single_selection=Make%3APorsche%2CModel%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn=4"

mpurl1 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw="
make = "Porsche"
plus = "+"
model = "911"
mpurl2 = "&rt=nc&LH_BIN=1&UF_single_selection=Make%3A"
mpurl3 = "%2C"
mpurl4 = "%3A911&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60625&_fspt=160441&_fspt=1&_pgn="
second = "2"
mpurl = paste0(mpurl1,make,plus,model,mpurl2,make,mpurl3,model,mpurl4,second)
mpurl




page1html = read_html(page1)
page2html = read_html(page2)
page3html = read_html(page3)
page4html = read_html(page4)
page1price = priceadjust(getprice(page1html))
page2price = priceadjust(getprice(page2html))
page3price = priceadjust(getprice(page3html))
page4price = priceadjust(getprice(page4html))
page1listing = gettitle(page1html)
page2listing = gettitle(page2html)
page3listing = gettitle(page3html)
page4listing = gettitle(page4html)

pricefunc = function(x) {
  priceadjust(getprice(x))
}




page1df = data.frame("Listing" = page1listing,   "Price" = page1price)
page2df = data.frame("Listing" = page2listing,    "Price" = page2price)
page3df = data.frame("Listing" = page3listing,     "Price" = page3price)
page4df = data.frame("Listing" = page4listing,       "Price" = page4price)
fulldataframe = rbind(page1df, page2df, page3df, page4df)

page1year = yearget(page1listing)
page2year = yearget(page2listing)
page3year = yearget(page3listing)
page4year = yearget(page4listing)


yppage1 = data.frame("Year" = page1year, "Price" = page1price)
yppage2 = data.frame("Year" = page2year, "Price" = page2price)
yppage3 = data.frame("Year" = page3year, "Price" = page3price)
yppage4 = data.frame("Year" = page4year, "Price" = page4price)

graphdf = rbind(yppage1, yppage2, yppage3, yppage4)
graphdf



ggplot(graphdf, aes(x = Year, y = Price)) + geom_point() + labs(title = "Vehicle Price Vs. Vehicle Year") + scale_y_continuous("Price", limits = c(0,500000)) + scale_x_continuous("Model Year")



```




```{r,eval = FALSE}
    finalurl = paste0(url1,input$make, plus, input$model, url2, input$make, url3, input$model, url4, input$zip, url5,input$length)
    url1 = "https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw="
    plus = "+"
    url2 = "&rt=nc&LH_BIN=1&UF_single_selection=Make%3A"
    url3 = "%2CModel%3A"
    url4 = "&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos="
    url5 = "&_fspt=160441&_fspt=1&_pgn="
```
```{r}
library("xml2")
```


```{r, eval=FALSE}
one = "1"
almostfinalurl = paste0(url1, plus, url2, url3, url4, url5,one)
almostfinalurl

```

```{r}
"https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Honda+Civic&rt=nc&LH_BIN=1&UF_single_selection=Make%3AHonda%2CModel%3ACivic&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60441&_fspt=1"
```

```{r}
https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Honda+Civic&rt=nc&LH_BIN=1&UF_single_selection=Make%3AHonda%2CModel%3ACivic&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60441&_fspt=1&_ipg=100
```
```{r}
https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_from=R40&_nkw=Honda+Civic&rt=nc&LH_BIN=1&UF_single_selection=Make%3AHonda%2CModel%3ACivic&UF_context=finderType%3AVEHICLE_FINDER&_sacat=6001&_stpos=60441&_fspt=1&_ipg=100
```

